package com.example.dietjoggingapp.database.domains

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class Nutrients(
    var monousatFat: Float? = null,
    var gluten: Float? = null,
    var transFat: Float? = null,
    var mannitol: Float? = null,
    var caloriesKCal: Float? = null,
    var sugarAlcohols: Float? = null,
    var protein: Float? = null,
    var fat: Float? = null,
    var maltitol: Float? = null,
    var cholesterol: Float? = null,
    var vitaminB12: Float? = null,
    var zinc: Float? = null,
    var phosphorus:Float? = null,
    var totalCarbs: Float? = null,
    var alcohol: Float? = null,
    var fiber: Float? = null,
    var vitaminC: Float? = null,
    var phyticAcid: Float? = null,
    var vitaminE: Float? = null,
    var vitaminD: Float? = null,
    var magnesium: Float? = null,
    var inositol: Float? = null,
    var diabetesCarbs: Float? = null,
    var vitaminK: Float? = null,
    var polyunsatFat: Float? = null,
    var sodium: Float? = null,
    var folate: Float? = null,
    var vitaminA: Float? = null,
    var diabetesCarbsADA:Float? =  null,
    var sugar: Float? = null,
    var caloriesKJ: Float? = null,
    var potassium: Float? = null,
    var conjugatedLinoleicAcid: Float? = null,
    var manganese: Float? = null,
    var sorbitol: Float? = null,
    var addedSugar: Float? = null,
    var vitaminB1: Float? = null,
    var choline: Float? = null,
    var lactitol: Float? = null,
    var vitaminB2: Float? = null,
    var caffeine: Float? = null,
    var vitaminB3: Float? = null,
    var omega3Fat: Float? = null,
    var selenium: Float? = null,
    var vitaminB5: Float? = null,
    var vitaminB6: Float? = null,
    var copper: Float? = null,
    var xylitol: Float? = null,
    var isomalt: Float? = null,
    var calcium: Float? = null,
    var netCarbs: Float? = null,
    var omega6Fat: Float? = null,
    var saturatedFat: Float? = null,
    var iron: Float? = null,
    var starch: Float? = null,
    var pinitol: Float? = null,
    var erythritol: Float? = null
) : Parcelable
